version: "3"

services:
  web:
    image: ledger
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: ledger
    volumes:
      - .:/ledger
    links:
      - redis:redis
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:latest
    expose:
      - 6379

    volumes:
      - redisdata:/data

volumes:
  redisdata: