# Generated by Django 4.0.3 on 2022-04-10 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 7, 22, 44, 556829)),
        ),
    ]
