# Generated by Django 4.0.3 on 2022-04-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
