# Generated by Django 4.0.3 on 2022-04-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transactions_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_type',
        ),
    ]
